### ISSUE TITLE
Android Manifest Error After adding this dependency.

### ISSUE THREAD

**Issue by doilio** [santalu/maskara#17]
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-30:19 to override.
```

![capture](https://user-images.githubusercontent.com/38020305/51671782-6f280e00-1fd2-11e9-9358-55618cdf6a9d.PNG)

**Comment by doilio** [comment]
version 1.1.1 Isn't working.
Only works when I use 

 `   implementation 'com.github.santalu:mask-edittext:1.0.9'`

**Comment by doilio** [comment]
Also, when I use the mask with a fixed number on the left, it always ends up eating my first number
`app:met_mask="+258(##) ## ## ###"`
Instead of +258(82) 12 34 567
It Shows:
+258(21) 23 45 675

**Comment by santalu** [comment]
Hi, Sorry for the late reply.
AndroidX is implemented with version **1.1.0** and later. So if you are not using androidx please use **1.0.9** and previous releases.
I'll look into your issue. It should not happen in latest version

**Comment by Vagonn** [comment]
@santalu any updates with this issue?

**Comment by enaannan** [comment]
@doilio how did you fix that issue?
