### ISSUE TITLE
Strange behaviour deleting and writing some characters more times (twice or three)

### ISSUE THREAD

**Issue by a-ferrari** [santalu/maskara#18]
Strange behaviour: use this example
   <com.santalu.maskedittext.MaskEditText
            android:id="@+id/etPhoneNumber"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="some text"
            **android:inputType="text"
            app:met_mask="## ## ## ## ## ## ## ##"**/>

At runtime, put some characters, than delete some of them using back button, do this action (put some characters than delete some ones) more times (twice or three).
As result i see some characters repeated.

**Comment by a-ferrari** [comment]
Version 1.0.9 works

**Comment by santalu** [comment]
Hi, sorry for the late reply.
Is the issue happening on latest version **1.1.0**?

**Comment by a-ferrari** [comment]
> Hi, sorry for the late reply.
> Is the issue happening on latest version **1.1.0**?

Hi, yes either 1.1.0 and 1.1.1 are affected
