### ISSUE TITLE
Support for multi line

### ISSUE THREAD

**Issue by omidraha** [santalu/maskara#3]
Apply mask on the each line:

```
<com.santalu.maskedittext.MaskEditText
	android:id="@+id/phones_input"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	android:inputType="textMultiLine|phone"
	android:scrollbars="vertical"
	android:minLines="4"
	android:maxLines="4"
	android:lines="4"
	app:mask="+90(###) ### ## ##"/>

```

**Comment by santalu** [comment]
I'll work on this as soon as i get a free time. But in the mean time anyone welcome to make a pull request.

**Comment by omidraha** [comment]
Why `wontfix` ?

**Comment by santalu** [comment]
Hi. I don't think there's any point in doing this since you can always use multiple edittext's. Don't you think?

**Comment by omidraha** [comment]
Hi, 
The one `textMultiLine` gets less space than multiple `edittext` and have better UI.
And also when one db model field is map to it.
And manipulating one view field as  `textMultiLine` is easer than multi `edittext`
